[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[dev]
  framework = "#custom"
  command = "npm run dev -- --port 8891"
  targetPort = 8891

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
